FROM oven/bun:1-alpine AS builder
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_AMO_SUBDOMAIN
ARG VITE_AMO_CLIENT_ID
ARG VITE_AMO_CLIENT_SECRET
ARG VITE_AMO_ACCESS_TOKEN

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_AMO_SUBDOMAIN=$VITE_AMO_SUBDOMAIN
ENV VITE_AMO_CLIENT_ID=$VITE_AMO_CLIENT_ID
ENV VITE_AMO_CLIENT_SECRET=$VITE_AMO_CLIENT_SECRET
ENV VITE_AMO_ACCESS_TOKEN=$VITE_AMO_ACCESS_TOKEN

RUN bun run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
